name: "Automated Build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Download source"
        uses: actions/checkout@v3

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: "Setup compiler toolchain"
        run: sudo apt install clang zlib1g-dev

      - name: "dotnet publish (Release, Windows, x64)"
        run: dotnet publish -c:Release -o publish/win-x64/ -r:win-x64 --no-self-contained

      - name: "dotnet publish (Release, Windows, x64, self contained)"
        run: dotnet publish -c:Release -o publish/win-x64-sc/ -r:win-x64 --self-contained  -p:PublishSingleFile=true -p:PublishTrimmed=true

      # - name: "dotnet publish (Release, Windows, x64, AoT)"
      #   run: dotnet publish -c:Release -o publish/win-x64-aot/ -r:win-x64 -p:PublishAot=true

      - name: "dotnet publish (Release, Linux, x64)"
        run: dotnet publish -c:Release -o publish/linux-x64/ -r:linux-x64 --no-self-contained

      - name: "dotnet publish (Release, Linux, x64, self contained)"
        run: dotnet publish -c:Release -o publish/linux-x64-sc/ -r:linux-x64 --self-contained  -p:PublishSingleFile=true -p:PublishTrimmed=true

      - name: "dotnet publish (Release, Linux, x64, AoT)"
        run: dotnet publish -c:Release -o publish/linux-x64-aot/ -r:linux-x64 -p:PublishAot=true

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            publish/*/VDFparse.exe
            publish/*/VDFparse
